import AppKit

/// What a poll observed about a copy: where it came from, and whether the
/// pasteboard really carried files. File-ness travels with the capture because
/// it cannot be recovered afterwards — the TEXT `/etc/hosts` and a copy of the
/// FILE `/etc/hosts` produce identical content, and guessing wrong turns a
/// pasted path into a pasted file.
struct CopySource {
    let name: String?
    let bundleID: String?
    /// True only when this exact change carried file URLs. See `Item.isFileCopy`.
    let isFileCopy: Bool

    init(name: String?, bundleID: String?, isFileCopy: Bool = false) {
        self.name = name
        self.bundleID = bundleID
        self.isFileCopy = isFileCopy
    }
}

/// What a poll found on the pasteboard, already classified — the watcher owns
/// the flavor-priority rules so consumers never re-read the pasteboard.
enum CopiedContent {
    case text(string: String, html: String?, rtf: Data?)
    case image(Data)
}

/// Watches the pasteboard and reports new copies.
///
/// macOS has no change notification for the pasteboard, so polling
/// `changeCount` is the only mechanism — every clipboard manager does this.
@MainActor
final class ClipboardWatcher {
    /// Marker types from the nspasteboard.org convention: concealed flags
    /// password-manager secrets, transient flags data clipboard managers must
    /// not store, auto-generated flags content a utility produced rather than
    /// the user. Anything carrying one of them is never recorded.
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private static let markerTypes = [concealedType, transientType, autoGeneratedType]

    var onCopy: ((CopiedContent, CopySource) -> Void)?

    /// Rich-flavor fragments (HTML, RTF) beyond this many BYTES are dropped,
    /// not truncated — a cut-off document would just fail to parse later.
    /// Bytes, not characters: the two flavors arrive as String and Data, and
    /// one cap that means one thing for each bounds nothing. Counting UTF-8
    /// also keeps a 300KB HTML string off a full grapheme walk on the poll path.
    private let flavorCap = 300_000
    /// Images over this fall through to the string path — drop, not truncate,
    /// for the same reason as `flavorCap`: half an image is no image.
    private let imageCap = 10_000_000
    /// A copy of more files than this is recorded as ordinary text, never as a
    /// file copy: a capped list would paste a silent subset of the selection,
    /// and an uncapped one would store a wall of paths that `Item.fileURLs`
    /// refuses anyway. Paths at least stay readable and pasteable as text.
    private let fileCountCap = 64

    private let pasteboard: NSPasteboard
    private let frontmostApplication: () -> CopySource
    private var lastChangeCount: Int
    private var timer: Timer?
    /// Held while running. An LSUIElement app with no visible window is the
    /// canonical App Nap target, and a napped poll timer loses every copy made
    /// between two throttled wakeups — permanently, because the pasteboard
    /// only ever exposes its latest state.
    private var activity: NSObjectProtocol?

    /// - Parameters:
    ///   - pasteboard: injectable so tests can use a private pasteboard.
    ///   - frontmostApplication: injectable so tests can fake the copy source.
    init(
        pasteboard: NSPasteboard = .general,
        frontmostApplication: @escaping () -> CopySource = ClipboardWatcher
            .systemFrontmostApplication
    ) {
        self.pasteboard = pasteboard
        self.frontmostApplication = frontmostApplication
        self.lastChangeCount = pasteboard.changeCount
    }

    func start(interval: TimeInterval = 0.5) {
        stop()
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            // Synchronously, not via Task: a hop to a later main-actor turn
            // lets a copy land between the callback and the poll, and the
            // resync below would then swallow it as our own write.
            MainActor.assumeIsolated { self?.poll() }
        }
        // Lets the system coalesce wakeups; a copy landing a beat late is fine.
        timer.tolerance = interval * 0.2
        // .common, not .default: tracking and modal run loops (scrolling the
        // list, dragging the divider, the menu bar menu, NSOpenPanel in
        // Settings) otherwise stop polling for as long as they are up, and
        // every copy made meanwhile is lost.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer

        activity = ProcessInfo.processInfo.beginActivity(
            options: .userInitiatedAllowingIdleSystemSleep,
            reason: "Polling the pasteboard for new copies"
        )
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        if let activity {
            ProcessInfo.processInfo.endActivity(activity)
            self.activity = nil
        }
    }

    /// Runs `write` — a Backpocket pasteboard write — without recording it.
    /// Backpocket's own writes must not be recorded: pasting an item would
    /// re-record it attributed to the app pasted into.
    ///
    /// The poll first is the whole point. A change the timer has not seen yet
    /// (the user copies in Safari, then immediately presses the hotkey) is
    /// still pending on the pasteboard; resyncing without draining it first
    /// would discard that copy forever, since the pasteboard only ever exposes
    /// its latest state.
    func suppressingOwnWrite(_ write: () -> Void) {
        poll()
        write()
        skipCurrentChange()
    }

    /// The unsafe half of `suppressingOwnWrite`, and only meaningful as its
    /// second step: called on its own it resyncs past every change since the
    /// last poll, not just Backpocket's. Callers want `suppressingOwnWrite`.
    func skipCurrentChange() {
        lastChangeCount = pasteboard.changeCount
    }

    func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if pasteboard.types?.contains(where: Self.markerTypes.contains) == true { return }

        let source = frontmostApplication()
        if IgnoredApps.contains(source.bundleID) { return }

        let text = pasteboard.string(forType: .string).flatMap {
            $0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? nil : $0
        }

        // Rich apps put a bitmap rendition beside the text on every copy
        // (Excel cells, Word shapes); there the text is the searchable,
        // pasteable truth. The image wins only with no text at all — or when
        // the text is just a web URL, which is how browsers ship a copied
        // image. WebLink, not a local rule: dropping the text is only safe
        // where Item would agree it was a link, and the two drifted apart
        // once — `mailto:` and `ftp:` counted here, not there, so the text was
        // discarded in favour of the bitmap and never showed up as a link.
        //
        // The text question comes first only for cost: reading the bitmap
        // copies it out of the pasteboard server, and the Excel and Word
        // copies above are precisely the ones where the answer is thrown away.
        if text == nil || WebLink.url(in: text!) != nil, let image = copiedImageData() {
            onCopy?(.image(image), source)
            return
        }

        // A Finder-style file copy puts the file's NAME on as text; recording
        // that would paste a bare title where the file belongs. The paths are
        // the truth, and pasting them back re-creates the original copy.
        if let copy = copiedFilePaths() {
            let fileSource = CopySource(
                name: source.name,
                bundleID: source.bundleID,
                isFileCopy: copy.isFileCopy
            )
            onCopy?(.text(string: copy.paths, html: nil, rtf: nil), fileSource)
            return
        }

        guard let string = text else { return }

        var html = pasteboard.string(forType: .html)
        if let candidate = html, candidate.utf8.count > flavorCap {
            html = nil
        }
        var rtf = pasteboard.data(forType: .rtf)
        if let candidate = rtf, candidate.count > flavorCap {
            rtf = nil
        }

        onCopy?(.text(string: string, html: html, rtf: rtf), source)
    }

    /// Image bytes when this change is a genuine image copy. A Finder file
    /// copy also exposes image renditions of image files — .fileURL marks
    /// those, and they must keep recording as text/paths, not as a bitmap.
    private func copiedImageData() -> Data? {
        let types = pasteboard.types ?? []
        guard !types.contains(.fileURL) else { return nil }
        guard types.contains(.png) || types.contains(.tiff) else { return nil }

        let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff)
        guard let data, data.count <= imageCap else { return nil }
        return data
    }

    /// Absolute paths, newline-separated, for a copy that carries file URLs,
    /// plus whether it may be recorded as a file copy. Reference URLs
    /// (`file:///.file/id=…`) resolve to real paths here, so nothing
    /// downstream has to know they existed.
    private func copiedFilePaths() -> (paths: String, isFileCopy: Bool)? {
        let urls =
            pasteboard.readObjects(
                forClasses: [NSURL.self],
                options: [.urlReadingFileURLsOnly: true]
            ) as? [URL] ?? []
        guard !urls.isEmpty else { return nil }

        let paths = urls.map(\.path).filter { !$0.isEmpty }
        guard !paths.isEmpty else { return nil }

        let capped = paths.count > fileCountCap
        return (paths.prefix(fileCountCap).joined(separator: "\n"), !capped)
    }

    /// Polling runs up to one interval after the copy, so if the user switches
    /// apps immediately the source can be wrong. Unavoidable without a change
    /// notification; rare in practice.
    nonisolated static func systemFrontmostApplication() -> CopySource {
        let app = NSWorkspace.shared.frontmostApplication

        // Backpocket itself and the login window are meaningless as sources.
        let meaningless = [Bundle.main.bundleIdentifier, "com.apple.loginwindow"]
        guard let bundleID = app?.bundleIdentifier, !meaningless.contains(bundleID) else {
            return CopySource(name: nil, bundleID: nil)
        }

        return CopySource(name: app?.localizedName, bundleID: bundleID)
    }
}
